### PR TITLE
Add Hubspot job application form

### PR DESCRIPTION
**Pull request by mitchmac**
As a Hiring Manager
I can gather applications in HubSpot

Each application has its own form in HubSpot.

### CODE REVIEW

**Comment by DirtyF** [comment]
@mitchmac Sorry I lack context, what is it for?

**Comment by mitchmac** [comment]
@DirtyF Folks had mentioned that receiving job applications via email can make it difficult to stay on top of submissions. This embeds a Hubspot form that we can test to see if it makes collecting submissions easier.

**Comment by DirtyF** [comment]
@mitchmac OK, I don't know what the expected workflow is, I can see the form on the /job-aplication URL, submitted a fake application to test the form. 

Job Application

**Comment by DirtyF** [comment]
@gregdferrell Do you want this form to be always active, even without job openings? Do you want a form per offer?

**Comment by gregdferrell** [comment]
Thanks Mitch. I'd like to tweak the Hubspot form.

Once that's done I'll make the necessary commits to wire it up to our careers page & job postings workflow.

**Comment by gregdferrell** [comment]
> @gregdferrell Do you want this form to be always active, even without job openings? Do you want a form per offer?

Good question. I don't really want it active if there are no job openings. I've instructed people to email careers@forestry.io in the past if they want to apply and there are no openings.

I think ideally we'd have an application/form per job posting but I'm fine to go with what is simplest for now. @mitchmac it looks like it should be simple enough to add a custom form to each job opening, right?

**Comment by DirtyF** [comment]
> I don't really want it active if there are no job openings

OK, so just remember in your Todo to unpublish the page in Forestry then.

**Comment by DirtyF** [comment]
Given each form has an ID, we could add that ID as a key in the offer link to `apply-{{form-id}}`
You'll need to manually create the form in HubSpot?

**Comment by gregdferrell** [comment]
Yes I'm looking at the route of adding a unique form in Hubspot per job opening. Then we can add the form to the existing job opening markdown pages.

**Comment by DirtyF** [comment]
We could also create a shortcode with the formId as the param to insert the form on the offer page.

**Comment by gregdferrell** [comment]
> We could also create a shortcode with the formId as the param to insert the form on the offer page.

Can you push that up so I can see?

**Comment by gregdferrell** [comment]
Ok @mitchmac @DirtyF 

I've added the form to the actual job posting. I'm ok with doing this for each posting, since this is a stop-gap solution and we'll likely be getting an applicant tracking system soon and this workflow will change again.

Does this look good? Frank I like your idea too if you want to take a crack at that. I don't have time at the moment.

**Pull request merged**
